### ISSUE TITLE
Can you add option for simple fragment?

### ISSUE THREAD

**Issue by paulocoutinhox** [kroegerama/barcode-kaiteki#1]
Hi,

Can you add option for simple fragment, instead of dialogs, alerts etc?

Thanks.

**Comment by kroegerama** [comment]
Sure, version 1.0.2 contains a simple Fragment. You can use it just like the Dialogs. Implement `BarcodeResultListener` in your Activity or parent Fragment. Then you can create/show a BarcodeFragment:

```kotlin
val barcodeFragment = BarcodeFragment.makeInstance(
    formats = listOf(BarcodeFormat.QR_CODE),
    barcodeInverted = false
)
supportFragmentManager.beginTransaction()
    .replace(R.id.container, barcodeFragment)
    .commit()
```
