### ISSUE TITLE
Barcode detection not working (Android 10, Pixel 3XL)

### ISSUE THREAD

**Issue by kroegerama** [kroegerama/barcode-kaiteki#4]
See #3: @alvindizon 
I was able to reproduce this on my Pixel 3XL running Android 10. Logcat contains the following line:
`W/Gralloc3: allocator 3.x is not supported`

Will update/close this issue, if I find out more about this...

**Comment by kroegerama** [comment]
May be related to [this issue](https://issuetracker.google.com/issues/80454351)

**Comment by kroegerama** [comment]
Fixed in commit b452839bf22783074d67e6fb26d5898563bd7c1c by downgrading `androidx.camera` from `1.0.0-alpha05` to `1.0.0-alpha03`.
I'll leave this open until I am able to use a newer version (waiting for beta/rc at least)

**Comment by ptsiogas** [comment]
@kroegerama any news with that?

**Comment by kroegerama** [comment]
Thanks for your reminder! I just published an update of barcode-kaiteki (`1.2.0`).

* available via MavenCentral
* uses CameraX 1.0.0 stable

Feel free to open a new issue, if you encounter any errors :)

**Comment by shamshadpattani** [comment]
E/ActivityThread: Failed to find provider info for com.oplus.statistics.provider

**Comment by shamshadpattani** [comment]
not  scanning show error like
E/ActivityThread: Failed to find provider info for com.oplus.statistics.provider
E/OplusStatistics--: IllegalArgumentException:java.lang.IllegalArgumentException: Unknown URL content://com.oplus.statistics.provider/track_event

**Comment by e1sep0** [comment]
> E/ActivityThread: Failed to find provider info for com.oplus.statistics.provider

The same issue, camera in webview opens, but paused and works only while pressing on image

**Comment by Dumankrg2019** [comment]
> 

Hello. How did you decide this problem?

**Comment by Dumankrg2019** [comment]
> not scanning show error like E/ActivityThread: Failed to find provider info for com.oplus.statistics.provider E/OplusStatistics--: IllegalArgumentException:java.lang.IllegalArgumentException: Unknown URL content://com.oplus.statistics.provider/track_event

Hello. How did you decide this problem?
