### ISSUE TITLE
Update ConstraintLayout 2.0.0-beta2

### ISSUE THREAD

**Issue by BsBrabi** [kroegerama/barcode-kaiteki#6]
Since I integrated your barcode scanner library, some of my layouts are affected by bugs of ConstraintLayout v2.0.0-beta2. The issues were fixed with [v2.0.0-beta3](https://androidstudio.googleblog.com/2019/10/constraintlayout-200-beta-3.html).

To fix the issues, I need to update the ConstraintLayout dependecy in my app to at least 2.0.0-beta3.

It would be great if you can provide a new library version with updated dependencies, so that my app does not depend on the library's version of ConstraintLayout.

**Comment by kroegerama** [comment]
I just published an update of barcode-kaiteki (`1.2.0`).

* uses ConstraintLayout 2.0.4 stable
* available via MavenCentral
* uses CameraX 1.0.0 stable

Feel free to create a new issue, if you run into any problem.
