### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by wewewe718** [kroegerama/barcode-kaiteki#9]
The latest release was more than a year ago. It seems that the repository is abandoned. Am I wrong?

**Comment by HoinzeyBear** [comment]
While there is no recent work on this repo, the author seems to be very active on Git.

**Comment by kroegerama** [comment]
Sorry, I just couldn't find any time to maintain this repo for some time. But I just brought the project back to life with an update to version `1.2.0`. 🚀 

* available via MavenCentral
* uses CameraX 1.0.0 stable

Feel free to create a new issue, if you run into any problem.
